name: cio_mass_cytometry
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-jsonvalidate
  - r-tidyverse
  - r-irkernel
  - r-umap
  - r-uwot
  - r-rjson
  - r-ggpubr
  - libxml2
  - cairo
  - bioconductor-flowsom
  - bioconductor-flowcore
  - bioconductor-catalyst
  - bioconductor-diffcyt
  - bioconductor-limma
  - jupyterlab
  - pandas
  - scikit-learn
  - plotnine
  - seaborn
  - openpyxl
  - pyarrow

