name: cio_mass_cytometry
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-jsonvalidate=1.1.0
  - r-tidyverse=1.3.1
  - r-irkernel=1.1.1
  - r-umap=0.2.7.0
  - r-uwot=0.1.10
  - libxml2=2.9.10
  - cairo=1.16.0
  - bioconductor-flowsom=1.22.0
  - bioconductor-flowcore=2.2.0
  - bioconductor-catalyst=1.14.0
  - bioconductor-diffcyt=1.10.0
  - bioconductor-limma=3.46.0
  - jupyterlab=3.0.14
